steps:
  - label: ":books: Build spec"
    command:
      # Install package dependencies
      - apk add nodejs npm python git
      # Install the node and python dependencies necessary to build the spec
      - npm i
      - python3 -m venv env && . env/bin/activate
      - pip install -r scripts/requirements.txt
      # Pull all git submodules, required for the hugo theme
      - git submodule update --init --recursive
      # Build the spec
      - /bin/sh -c "scripts/generate-matrix-org-assets"
    artifact_paths:
      - assets.tar.gz
    plugins:
      - docker#v3.0.1:
          # The Hugo docker image recommended by the Hugo project:
          # https://gohugo.io/getting-started/installing/#docker
          # We use the extended (ext-) version for SCSS support.
          image: klakegg/hugo:ext-alpine

  - label: "rebuild matrix.org"
    trigger: "matrix-dot-org"
    async: true
    branches: "master"
