steps:
  - label: ":books: Build spec"
    command:
      # Install package dependencies
      - apk add nodejs npm python git hugo
      # Install the node and python dependencies necessary to build the spec
      - npm i
      - python3 -m venv env && . env/bin/activate
      - pip install -r scripts/requirements.txt
      # Pull all git submodules, required for the hugo theme
      - git submodule update --init --recursive
      # Build the spec
      - scripts/generate-matrix-org-assets
    artifact_paths:
      - assets.tar.gz
    plugins:
      - docker#v3.7.0:
          image: alpine

  - label: "rebuild matrix.org"
    trigger: "matrix-dot-org"
    async: true
    branches: "master"
